### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by matthewmummert5** [ssrlive/mypass#1]
Hi,

I noticed you don't have a license for this repo.  I'm assuming that no license means "all rights reserved" and you don't want anybody using your code. Is that your intention? If that is your intention, could we negotiate over a private channel for me to get a license to try out your app?

Otherwise, if your intention was to make this app free/libre software, I would suggest maybe the MIT or GPL-3 license.

Thanks

**Comment by ssrlive** [comment]
Github default license. I will add this.

PS: I have added GPLv3 license.
